channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.4.13
  - certifi=2020.6.20
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - python=3.6.10
  - python_abi=3.6
  - readline=7.0
  - setuptools=36.4.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.29.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - backports-functools-lru-cache==1.6.4
    - backports-weakref==1.0.post1
    - bleach==1.5.0
    - boto==2.49.0
    - boto3==1.17.54
    - botocore==1.20.54
    - bz2file==0.98
    - chardet==3.0.4
    - cheroot==8.5.2
    - cherrypy==17.4.2
    - contextlib2==0.6.0.post1
    - crypto==1.4.1
    - cython==0.23.4
    - enum34==1.1.10
    - ez-setup==0.9
    - git+https://github.com/facebookresearch/fastText.git
    - funcsigs==1.0.2
    - gensim==3.8.3
    - html5lib==0.9999999
    - idna==2.10
    - jaraco-functools==2.0
    - jmespath==0.10.0
    - markdown==3.1.1
    - mock==3.0.5
    - more-itertools==5.0.0
    - naked==0.1.31
    - numpy==1.16.1
    - pandas==0.24.2
    - pip==21.0.1
    - portend==2.6
    - protobuf==3.12.2
    - pybind11==2.6.2
    - pycrypto==2.6.1
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - repoze-lru==0.7
    - requests==2.24.0
    - requests-cache==0.5.2
    - routes==2.5.1
    - s3transfer==0.4.0
    - scikit-learn==0.20.4
    - scipy==1.2.3
    - selectors2==2.0.2
    - shellescape==3.8.1
    - six==1.15.0
    - smart-open==1.10.1
    - tempora==1.14.1
    - tqdm==4.47.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - xlrd==1.2.0
    - zc-lockfile==2.0
